### ISSUE TITLE
Support all spl-tokens

### ISSUE THREAD

**Issue by jpbogle** [cardinal-labs/hydra-ui#2]
Hydra-ui should support all fungible tokens not just native sol

This can be achieved by modifying this to look up the mint account for the fanout, deserializing it and converting the decimals to UI amount (shift by decimals).
https://github.com/cardinal-labs/hydra-ui/blob/b40e4ee855cca2d61b1f29f67d5761b3410f295c/hooks/useFanoutData.ts.ts#L28-L29

A token-list provider, can also be used to populate the token metadata as down here 
https://github.com/cardinal-labs/cardinal-staking-ui/blob/1af2b9c927803cb0ae405d6de49b955fd68e859b/providers/TokenListProvider.tsx#L32

**Comment by TheCurryMan** [comment]
Added with #8 using SPL Fanout Mints
