### ISSUE TITLE
Creation of hydra wallet arbitrary number of decimal shares

### ISSUE THREAD

**Issue by jpbogle** [cardinal-labs/hydra-ui#3]
Right now it only supports shares of 100

It should allow input of any decimal length share value, and scale up the total shares by that number

i.e. if i set a shares to 33.3 it will make totalShares 1000 and share 333 or if I do 33.33 it will do 10000 and share 3333

**Comment by TheCurryMan** [comment]
Changing to support entering custom share amount + checks to ensure form shares sum up to total shares specified. 

https://github.com/cardinal-labs/hydra-ui/pull/6
